# Generated by Django 5.2.14 on 2026-06-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('prioridade', models.CharField(blank=True, max_length=50, null=True)),
                ('status_tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('responsavel_nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
