# Generated by Django 5.2.14 on 2026-06-01 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sector', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_setor',
            field=models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='id_projeto',
            field=models.ForeignKey(db_column='id_projeto', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
