# Generated by Django 5.2.14 on 2026-06-01 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id_oficio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sequencial', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('assunto', models.CharField(max_length=255)),
                ('data_oficio', models.DateField()),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'oficios',
            },
        ),
    ]
