# Generated by Django 5.2.14 on 2026-06-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateField()),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_dado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indicadores',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
    ]
