# Generated by Django 5.2.14 on 2026-06-01 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_indicador',
            field=models.ForeignKey(blank=True, db_column='id_indicador', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.indicador'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_setor',
            field=models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector'),
        ),
    ]
