# Generated by Django 5.2.14 on 2026-06-01 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('senha_hash', models.CharField(max_length=255)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_acesso', models.CharField(max_length=50)),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricoSenhas',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_responsavel', models.ForeignKey(db_column='id_responsavel', on_delete=django.db.models.deletion.CASCADE, related_name='resets_realizados', to='users.users')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='resets_recebidos', to='users.users')),
            ],
            options={
                'db_table': 'historico_senhas',
            },
        ),
    ]
