# Generated by Django 6.1.1 on 2026-09-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pergunta_seguranca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='resposta_seguranca_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
